### ISSUE TITLE
regarding your java benchmark

### ISSUE THREAD

**Issue by thomasjungblut** [DouglasOrr/DouglasOrr.github.io#1]
Thanks for writing your blog post about making stuff unique, learned a lot about the c++ differences.
In Part 2 you discuss a java solution, being a JIT'd language you would need to pay some attention on warm-up. There's a good SO discussion about it: https://stackoverflow.com/questions/504103/how-do-i-write-a-correct-micro-benchmark-in-java

Maybe you can translate your benchmark to JMH or Caliper, I think that should give more reliable numbers.

**Comment by DouglasOrr** [comment]
_Thanks for this! Sorry I didn't get back to you sooner - I assumed I would be notified of events on this repo automatically, but wasn't, only just spotted it now..._

Good suggestion & thanks for the link - it reminds me how primitive my knowledge of the JVM is - and that microbenchmarking there is fiddly! My warmup approach was quite basic - I just logged the timing of each repeated run so I could look for the effect in post-hoc analysis (& then didn't spot any particular trend when looking at the data.) But it could definitely disadvantage the first configurations run in the inner loop (and it's probably not particularly reliable for a comparison between C++ & Java, which I did briefly make in the post).
